project:
  type: book

book:
  title: "GS_ResMeth_DemoBook"
  author: "Dr. Gordon Wright and the gang"
  date: "4/29/2025"

  chapters:
    - index.qmd
    - intro.qmd
    - demos.qmd
    - summary.qmd
    - webexercises.qmd
    - webr.qmd
    - downloadthis.qmd
    - references.qmd
    - part: Overview
      chapters:
        - text: Syllabus
          href: index.qmd
    - part: Week 01
      chapters:
        - text: Lecture
          href: week01/lecture.qmd
        - text: Lab
          href: week01/lab.qmd
        - text: DataSkills
          href: week01/dsk.qmd
        - text: Chapter 1 (RM)
          href: week01/WhatIsScience.qmd
        - text: Chapter 1 (Stats)
          href: week01/WhyStatistics.qmd
    # - part: Research Methods Textbook
    #   chapters:
    #     - text: "Chapter 1: Foundations"
    #       href: Crump-ResearchMethods/01-PsychScience.qmd
    #     - text: "Chapter 2: Getting Started"
    #       href: Crump-ResearchMethods/02-GettingStarted.qmd
    # - part: Stats Textbook
    #   chapters:
    #     - text: "Science Data"
    #       href: CRUMP/01-Science_Data.qmd
    #     - text: "Describing Data"
    #       href: CRUMP/02-Describing_Data.qmd
  page-footer:
    right: |
      This page is built with {{< fa brands r-project >}}, ☕, ❤️ and [Quarto](https://quarto.org/) <br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/littlemonkeylab/ps52007dslides.com)
    left: |
      Content {{< fa brands creative-commons >}} 2023 by Gordon Wright {{< fa brands orcid >}} <strong>ORCID</strong> [0000-0001-9424-5743](https://orcid.org/0000-0001-9424-5743). All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}<br>
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    background: "#000080"

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, include/gs_rm.scss, include/webex.css, include/webex.js]
    code-link: true
    mainfont: Atkinson Hyperlegible
    monofont: Source Code Pro
    toc: true
    toc-depth: 2
  pdf:
    mainfont: "Atkinson Hyperlegible"
    callout-appearance: simple
    include-in-header: 
      - include/gs_rm.tex
    filters: 
      - include/gs_rm.lua
    keep-tex: true
    



  
  