name: Render and Publish Quarto Book

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Quarto
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.7.29

    # Step 3: Set up R with caching
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        cache: true

    # Step 4: Install dependencies
    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("rmarkdown", "knitr"), repos = "https://cloud.r-project.org/")'

    # Step 5: Render the Quarto book
    - name: Render Quarto Book
      run: |
        quarto render

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
